apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: <WORKLOAD_CLUSTER_NAME>
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  configuration: |
      terraform {
        backend "s3" {
          bucket   = "k1-state-store-cn-demo-kukapd"
          key      = "registry/clusters/<WORKLOAD_CLUSTER_NAME>/infrastructure/provider-config/terraform.tfstate"
          endpoint = "https://objectstore.fra1.civo.com"

          region = "fra1"

          skip_credentials_validation = true
          skip_metadata_api_check     = true
          skip_region_validation      = true
          force_path_style            = true
        }
        required_providers {
          civo = {
            source  = "civo/civo"
            version = "~> 1.1.0"
          }
        }
      }
      provider "civo" {
        region = "<WORKLOAD_CLUSTER_REGION>"
      }
  credentials:
  - filename: gen-nothing
    source: None
    secretRef:
      namespace: crossplane-system
      name: civo-creds
      key: token
  - filename: .git-credentials
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: git-credentials
      key: creds
